ANSWER_KEY = {
    "general-knowledge-01": {
        1: {"type": "mcq", "answer": "Tokyo"},
        2: {"type": "mcq", "answer": "Ottawa"},
        3: {"type": "text", "answer": "Canberra"},
        4: {"type": "mcq", "answer": "Brasília"},
        5: {"type": "text", "answer": "Cairo"},
        6: {"type": "mcq", "answer": "Madrid"},
        7: {"type": "mcq", "answer": "Moscow"},
        8: {"type": "text", "answer": "Buenos Aires"},
        9: {"type": "mcq", "answer": "Seoul"},
        10: {"type": "text", "answer": "Rome"},
        11: {"type": "mcq", "answer": "Berlin"},
        12: {"type": "text", "answer": "New Delhi", "accepted": ["Delhi"]},
        13: {"type": "mcq", "answer": "Nairobi"},
        14: {"type": "text", "answer": "Wellington"},
        15: {"type": "mcq", "answer": "Mexico City"},
        16: {"type": "text", "answer": "Ankara"},
        17: {"type": "mcq", "answer": "Bangkok"},
        18: {"type": "text", "answer": "Stockholm"},
        19: {"type": "mcq", "answer": "Oslo"},
        20: {"type": "text", "answer": "Lisbon"},
        21: {"type": "mcq", "answer": "Beijing"},
        22: {"type": "text", "answer": "Athens"},
        23: {"type": "mcq", "answer": "Jakarta"},
        24: {"type": "text", "answer": "Abu Dhabi"},
        25: {"type": "mcq", "answer": "London"},
    },
    "verbal-reasoning-advanced-01": {
        1: {"type": "mcq", "answer": "Chisel : Sculptor"},
        2: {"type": "text", "answer": "Claustrophobia"},
        3: {"type": "mcq", "answer": "Aloof"},
        4: {"type": "mcq", "answer": "Mischievous"},
        5: {
            "type": "text",
            "answer": "To give up or surrender",
            "accepted": ["give up", "surrender", "quit", "admit defeat", "stop trying"],
        },
        6: {"type": "mcq", "answer": "Treacherous"},
        7: {
            "type": "text",
            "answer": "The committee has submitted its report",
            "accepted": ["the committee submitted its report"],
        },
        8: {"type": "mcq", "answer": "Steam : Geyser"},
        9: {"type": "mcq", "answer": "Commonplace"},
        10: {"type": "text", "answer": "Inevitable"},
        11: {"type": "mcq", "answer": "Omnipresent"},
        12: {
            "type": "text",
            "answer": "To join a popular activity or trend",
            "accepted": ["join a popular trend", "follow the crowd", "join in with a popular trend"],
        },
        13: {"type": "mcq", "answer": "Bird : Nest"},
        14: {"type": "text", "answer": "Conscience"},
        15: {"type": "mcq", "answer": "Loquacious"},
        16: {"type": "mcq", "answer": "with"},
        17: {"type": "text", "answer": "Polymath"},
        18: {"type": "mcq", "answer": "Transient"},
        19: {
            "type": "text",
            "answer": "Each of the students is responsible",
            "accepted": ["each student is responsible", "every student is responsible"],
        },
        20: {"type": "mcq", "answer": "Scene : Play"},
        21: {"type": "mcq", "answer": "Succinct"},
        22: {
            "type": "text",
            "answer": "A seemingly bad event that has a good outcome",
            "accepted": [
                "a good thing that comes from a bad situation",
                "a positive outcome from a bad event",
                "something good coming from something bad",
            ],
        },
        23: {"type": "mcq", "answer": "Cemetery"},
        24: {
            "type": "text",
            "answer": "Polygyny",
            "accepted": ["having more than one wife", "the practice of having multiple wives"],
        },
        25: {"type": "mcq", "answer": "Homesickness"},
    },
    "logical-puzzles-01": {
        1: {"type": "text", "answer": "His son", "accepted": ["the man's son", "his son is in the portrait"]},
        2: {"type": "mcq", "answer": "20"},
        3: {"type": "text", "answer": "194"},
        4: {"type": "mcq", "answer": "No letter"},
        5: {"type": "text", "answer": "5", "accepted": ["5 minutes"]},
        6: {"type": "mcq", "answer": "Granddaughter"},
        7: {"type": "text", "answer": "Mary"},
        8: {"type": "mcq", "answer": "15"},
        9: {"type": "text", "answer": "A needle", "accepted": ["needle"]},
        10: {"type": "mcq", "answer": "6"},
        11: {"type": "text", "answer": "60 minutes", "accepted": ["60", "one hour", "an hour"]},
        12: {"type": "mcq", "answer": "21"},
        13: {"type": "text", "answer": "A bottle", "accepted": ["bottle"]},
        14: {"type": "mcq", "answer": "32"},
        15: {"type": "text", "answer": "9"},
        16: {"type": "mcq", "answer": "J"},
        17: {"type": "text", "answer": "A sponge", "accepted": ["sponge"]},
        18: {"type": "mcq", "answer": "9"},
        19: {"type": "text", "answer": "A stamp", "accepted": ["stamp"]},
        20: {"type": "mcq", "answer": "Monday"},
        21: {"type": "text", "answer": "A piano", "accepted": ["piano"]},
        22: {"type": "mcq", "answer": "Cow"},
        23: {"type": "text", "answer": "The letter m", "accepted": ["m"]},
        24: {"type": "mcq", "answer": "Meat"},
        25: {"type": "text", "answer": "3", "accepted": ["three"]},
    },
}
